language: ruby

rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby-19mode
  - rbx-2.1.1
  - 2.1.0-preview2
  - jruby-head
  - ruby-head

bundler_args: --without guard

matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
